"""Self-contained HTML report.

One file, no network, no CDN, no web fonts, opens from ``file://``. That matters
because the users this was built for work on clusters where standing up a server
and forwarding a port is awkward: a single file can be produced inside a batch
job, copied off with ``scp``, and attached to a pull request.

Autoescaping is on unconditionally and every corpus string additionally passes
through :func:`safe_snippet`, because everything rendered here came from data we
did not write.
"""

from __future__ import annotations

from typing import Any

from jinja2 import Environment, StrictUndefined

from ..fingerprint import Fingerprint
from ..models import Confidence, Severity
from ..runner import ScanResult
from .escaping import safe_snippet

_CSS = """
:root{--bg:#fbfbfa;--fg:#1a1a1a;--dim:#6b6b6b;--line:#e3e3e0;--card:#fff;
--red:#b3261e;--amber:#8a6100;--blue:#0b5cad;--green:#1f6b3a}
@media(prefers-color-scheme:dark){:root{--bg:#141414;--fg:#e8e8e6;--dim:#9a9a97;
--line:#2b2b2b;--card:#1b1b1b;--red:#ef6a5f;--amber:#d9a441;--blue:#6fb3f2;--green:#65c98a}}
*{box-sizing:border-box}
body{margin:0;padding:2rem 1.25rem 4rem;background:var(--bg);color:var(--fg);
font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}
.wrap{max-width:1000px;margin:0 auto}
h1{font-size:1.5rem;margin:0 0 .25rem}
h2{font-size:1.05rem;margin:2.25rem 0 .75rem;padding-bottom:.35rem;border-bottom:1px solid var(--line)}
.sub{color:var(--dim);font-size:.9rem;margin-bottom:1.5rem}
.banner{background:var(--card);border:1px solid var(--line);border-left:3px solid var(--amber);
padding:.75rem 1rem;border-radius:4px;margin:1rem 0;font-size:.9rem}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:.75rem}
.stat{background:var(--card);border:1px solid var(--line);border-radius:6px;padding:.75rem .9rem}
.stat .k{color:var(--dim);font-size:.75rem;text-transform:uppercase;letter-spacing:.04em}
.stat .v{font-size:1.25rem;font-weight:600;margin-top:.15rem}
table{width:100%;border-collapse:collapse;font-size:.9rem}
th{text-align:left;color:var(--dim);font-weight:500;font-size:.78rem;text-transform:uppercase;
letter-spacing:.04em;padding:.4rem .6rem;border-bottom:1px solid var(--line)}
td{padding:.5rem .6rem;border-bottom:1px solid var(--line);vertical-align:top}
.scroll{overflow-x:auto}
.sev{display:inline-block;width:.55rem;height:.55rem;border-radius:50%;margin-right:.4rem}
.blocking{background:var(--red)}.warning{background:var(--amber)}.info{background:var(--blue)}
code,.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.84em}
.ev{background:var(--card);border:1px solid var(--line);border-radius:4px;padding:.5rem .7rem;
margin:.35rem 0;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.8rem;
white-space:pre-wrap;word-break:break-word}
.loc{color:var(--dim);font-size:.75rem;margin-bottom:.2rem}
.dim{color:var(--dim)}
.pill{display:inline-block;background:var(--card);border:1px solid var(--line);border-radius:99px;
padding:.05rem .5rem;font-size:.75rem;color:var(--dim)}
details{margin:.5rem 0}summary{cursor:pointer;color:var(--dim);font-size:.85rem}
footer{margin-top:3rem;padding-top:1rem;border-top:1px solid var(--line);
color:var(--dim);font-size:.8rem}
"""

_TEMPLATE = """<!-- generated by dropoutt {{ pipeline_version }} -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy"
      content="default-src 'none'; style-src 'unsafe-inline'; img-src data:">
<title>dropoutt scan — {{ root_short }}</title>
<style>{{ css }}</style>
<div class="wrap">
<h1>dropoutt scan</h1>
<div class="sub mono">{{ root }}</div>

<div class="grid">
  <div class="stat"><div class="k">records</div><div class="v">{{ "{:,}".format(records) }}</div></div>
  <div class="stat"><div class="k">datasets</div><div class="v">{{ datasets|length }}</div></div>
  <div class="stat"><div class="k">findings</div><div class="v">{{ findings|length }}</div></div>
  <div class="stat"><div class="k">profile</div><div class="v">{{ profile }}</div></div>
</div>

<div class="banner">
  Every finding in this build is <strong>unverified</strong>. No measured effect size is
  attached to acting on any of them, because no calibration corpus exists yet. These are
  structural observations about your data, not predictions about your model.
  {% if not blocking_enabled %}
  No blocking verdict was issued because no target profile was declared.
  {% endif %}
</div>

{% if findings %}
<h2>Findings</h2>
<div class="scroll">
<table>
<tr><th>check</th><th>severity</th><th>count</th><th>detail</th><th>fix</th></tr>
{% for f in findings %}
<tr>
  <td class="mono">{{ f.check_id }}<br><span class="dim">{{ f.title }}</span></td>
  <td><span class="sev {{ f.severity.value }}"></span>{{ f.severity.value }}
      {% if f.would_block_under and not f.is_blocking %}
      <br><span class="dim">would block under {{ f.would_block_under|join(', ') }}</span>
      {% endif %}</td>
  <td class="mono">{{ "{:,}".format(f.count) if f.count else "—" }}
      {% if f.total_considered %}<br><span class="dim">{{ "%.2f%%"|format(f.rate * 100) }}</span>{% endif %}</td>
  <td>{{ f.detail }}
      {% if f.wasted_tokens %}<br><span class="dim">{{ "{:,}".format(f.wasted_tokens) }} tokens</span>{% endif %}</td>
  <td class="dim">{{ f.fix }}</td>
</tr>
{% endfor %}
</table>
</div>

<h2>Examples</h2>
{% for f in findings if f.evidence %}
<details {% if loop.first %}open{% endif %}>
  <summary>{{ f.check_id }} — {{ f.title }} ({{ f.evidence|length }} shown)</summary>
  {% for ev in f.evidence %}
  <div class="loc mono">{{ ev.source_file }}:{{ ev.source_index }}</div>
  <div class="ev">{{ ev.excerpt }}</div>
  {% if ev.partner_excerpt %}
  <div class="loc mono">matches{% if ev.score %} — Jaccard {{ "%.2f"|format(ev.score) }}{% endif %}</div>
  <div class="ev">{{ ev.partner_excerpt }}</div>
  {% endif %}
  {% endfor %}
</details>
{% endfor %}
{% endif %}

{% if overlap %}
<h2>Cross-dataset overlap</h2>
<p class="dim">Directional: read as “this share of <em>row</em> also appears in <em>column</em>”.
Containment of a small dataset inside a large one is the actionable case, and a symmetric
similarity score would hide it.</p>
<div class="scroll">
<table>
<tr><th>from</th><th>appears in</th><th>matched</th><th>of</th><th>share</th></tr>
{% for r in overlap %}
<tr><td class="mono">{{ r["from"] }}</td><td class="mono">{{ r["to"] }}</td>
<td class="mono">{{ "{:,}".format(r["matched"]) }}</td>
<td class="mono">{{ "{:,}".format(r["of"]) }}</td>
<td class="mono">{{ "%.1f%%"|format(r["fraction"] * 100) }}</td></tr>
{% endfor %}
</table>
</div>
{% endif %}

{% if budget %}
<h2>Token budget</h2>
{% if not has_tokenizer %}
<p class="dim">Estimated from a sample, because no <code>--model</code> was given. Character
counts are exact; tokens-per-character comes from a stratified sample.</p>
{% endif %}
<div class="scroll">
<table>
<tr><th>tokenizer</th><th>total tokens</th><th>tokens per word</th><th>premium</th></tr>
{% for e in budget %}
<tr><td class="mono">{{ e.name }}</td>
<td class="mono">{{ "{:,}".format(e.total) }}</td>
<td class="mono">{{ "%.2f"|format(e.tpw) }}</td>
<td class="mono">{% if e.premium > 0 %}+{{ "%.0f%%"|format(e.premium * 100) }}{% else %}—{% endif %}</td></tr>
{% endfor %}
</table>
</div>
{% endif %}

<h2>Datasets</h2>
<div class="scroll">
<table>
<tr><th>name</th><th>layout</th><th>files</th><th>records</th><th>licence</th></tr>
{% for d in datasets %}
<tr><td class="mono">{{ d.name }}</td><td class="mono">{{ d.layout or "—" }}</td>
<td class="mono">{{ d.files }}</td><td class="mono">{{ "{:,}".format(d.records) }}</td>
<td>{% if d.licence %}{{ d.licence }}{% else %}<span class="dim">not recorded</span>{% endif %}</td></tr>
{% endfor %}
</table>
</div>

{% if skipped %}
<h2>What you are not seeing yet</h2>
<p class="dim">Each of these names the single thing that would unlock it.</p>
<div class="scroll">
<table>
<tr><th>check</th><th>why not</th><th>unlock</th></tr>
{% for s in skipped %}
<tr><td class="mono">{{ s.check_id }}<br><span class="dim">{{ s.title }}</span></td>
<td>{{ s.reason }}</td><td class="mono dim">{{ s.unlock }}</td></tr>
{% endfor %}
</table>
</div>
{% endif %}

{% if degradations %}
<h2>Degraded</h2>
<ul class="dim">{% for d in degradations %}<li>{{ d }}</li>{% endfor %}</ul>
{% endif %}

<h2>Reproducibility</h2>
<div class="scroll">
<table>
{% for k, v in provenance %}
<tr><td class="dim">{{ k }}</td><td class="mono">{{ v }}</td></tr>
{% endfor %}
</table>
</div>

<footer>
dropoutt {{ pipeline_version }} · fingerprint <span class="mono">{{ fingerprint_id }}</span> ·
{{ "{:,}".format(records) }} records in {{ "%.1f"|format(elapsed) }}s<br>
This report may contain excerpts of your data, including anything sensitive that the scan
found. Personal data matched by the PII check is masked, but surrounding text is not.
</footer>
</div>
"""


def render(result: ScanResult, fp: Fingerprint, budget: Any = None) -> str:
    env = Environment(autoescape=True, undefined=StrictUndefined,
                      trim_blocks=True, lstrip_blocks=True)
    tpl = env.from_string(_TEMPLATE)

    findings = sorted(
        result.findings,
        key=lambda f: ({Severity.BLOCKING: 0, Severity.WARNING: 1, Severity.INFO: 2}
                       .get(f.severity, 3), f.check_id),
    )
    # Every excerpt goes through safe_snippet before Jinja sees it.
    for f in findings:
        for ev in f.evidence:
            ev.excerpt = safe_snippet(ev.excerpt)
            if ev.partner_excerpt:
                ev.partner_excerpt = safe_snippet(ev.partner_excerpt)

    overlap = []
    for f in findings:
        if f.check_id == "T1-OVERLAP-001":
            overlap = f.data.get("matrix", [])[:40]

    budget_rows = []
    if budget is not None and budget.estimates:
        for e in sorted(budget.estimates, key=lambda x: x.total_tokens_est):
            if e.failed:
                continue
            budget_rows.append({
                "name": e.name,
                "total": e.total_tokens_est,
                "tpw": e.tokens_per_word,
                "premium": budget.premium_vs_cheapest(e),
            })

    seen: set[str] = set()
    skipped = []
    for s in result.skipped:
        if s.reason in seen:
            continue
        seen.add(s.reason)
        skipped.append(s)

    root = result.ctx.root
    return tpl.render(
        css=_CSS,
        root=root,
        root_short=root.split("/")[-1] or root,
        records=result.records_scanned,
        datasets=fp.datasets,
        findings=findings,
        overlap=overlap,
        budget=budget_rows,
        has_tokenizer=result.ctx.tokenizer is not None,
        skipped=skipped,
        degradations=result.ctx.degradations,
        profile=result.ctx.profile.value,
        blocking_enabled=result.ctx.blocking_enabled,
        provenance=sorted(fp.provenance.items()),
        fingerprint_id=fp.fingerprint_id,
        pipeline_version=fp.pipeline_version,
        elapsed=result.elapsed,
    )
