"""Self-contained HTML report.

One file, no network, no CDN, no web fonts, opens from ``file://``. That matters
because the users this was built for work on clusters where standing up a server
and forwarding a port is awkward: a single file can be produced inside a batch
job and copied with ``scp`` when policy permits. By default it contains record
excerpts; ``--no-evidence`` removes excerpts and source locations.

Autoescaping is on unconditionally and every corpus string additionally passes
through :func:`safe_snippet`, because everything rendered here came from data we
did not write.

**The page describes before it complains.** It used to open with a list of
findings, which meant a reader who had just been handed a folder learned what
was wrong with it before learning what it was — and learned what it was only by
inference, since a finding mentions a property of the corpus exactly when that
property is broken. So composition comes first: what language, what shape,
whether it is already formatted, how big. The verdict is still above all of it,
because someone re-reading a failed CI run should not have to scroll, but it is
one line rather than a panel.

Then the findings, then the token budget, then the map. That order is what a
person actually asks in sequence: what is this, what is wrong with it, what will
it cost, and what is it missing.

What the page must not do is present the atlas's own labels as facts about the
data. See :mod:`dropoutt.report.summary` for why, and for the rule that a place
on the map is named by the reader's own record before it is named by a caption.
"""

from __future__ import annotations

from typing import Any

from jinja2 import Environment, StrictUndefined

from ..fingerprint import Fingerprint
from ..runner import ScanResult
from .escaping import safe_snippet
from .summary import ScanSummary, budget_method, budget_rows, build
from .theme import LOGO_SVG, stylesheet

_TEMPLATE = """<!-- generated by dropoutt {{ pipeline_version }} -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy"
      content="default-src 'none'; style-src 'unsafe-inline'; img-src data:">
<title>dropoutt — {{ root_short }}</title>
<style>{{ css|safe }}</style>
<div class="wrap">

<header class="masthead">
  {{ logo|safe }}
  <span class="wordmark">dropoutt</span>
  <span class="kind">dataset report</span>
  <span class="where">{{ root }}</span>
</header>

<div class="verdict {{ s.tone }}">
  <span class="dot"></span>
  <span class="headline">{{ s.verdict }}</span>
  {% if s.subtitle %}<span class="lead">{{ s.subtitle }}</span>{% endif %}
</div>

{# ---------------------------------------------------------------- 01 #}
<section>
  <div class="sechead"><span class="n">01</span><h2>What this corpus is</h2></div>
  <p class="secnote">Measured over every record that was read, before any
  question of what is wrong with it.</p>

  <div class="grid g4">
    <div class="card stat">
      <span class="k">Records</span>
      <span class="v">{{ "{:,}".format(s.records) }}</span>
      <span class="n">{{ s.datasets }} dataset{{ "" if s.datasets == 1 else "s" }}
        in {{ s.files }} file{{ "" if s.files == 1 else "s" }}</span>
    </div>
    <div class="card stat">
      <span class="k">Looks like</span>
      <span class="v" style="font-size:var(--t-20)">{{ s.profile }}</span>
      <span class="n">{{ s.profile_line or "layout could not be inferred" }}</span>
    </div>
    <div class="card stat">
      <span class="k">Tokens</span>
      <span class="v">{{ tokens_short }}</span>
      <span class="n">{% if s.tokens %}{{ token_note }}{% else %}no tokenizer available{% endif %}</span>
    </div>
    <div class="card stat">
      <span class="k">Average record</span>
      <span class="v">{{ "{:,}".format(c.mean_chars) }}<span class="muted" style="font-size:var(--t-14)"> chars</span></span>
      <span class="n">{{ "{:,}".format(c.total_words) }} words across the corpus</span>
    </div>
  </div>

  <div class="grid g2" style="margin-top:var(--s-12)">
    <div class="card">
      <h3>Languages</h3>
      {% if s.languages %}
      <p class="t13 muted">Share of records, from the language detector. Records
      it could not call are counted under <code>unknown</code>.</p>
      <div class="bars">
      {% for code, share in s.languages[:7] %}
        <div class="bar">
          <span class="label">{{ code }}</span>
          <span class="track"><span class="fill h{{ loop.index0 % 7 }}" style="width:{{ "%.1f"|format(share * 100) }}%"></span></span>
          <span class="v">{{ "%.1f%%"|format(share * 100) }}</span>
        </div>
      {% endfor %}
      </div>
      {% if s.languages|length > 7 %}
      <p class="t12 faint" style="margin-top:var(--s-12)">and
        {{ s.languages|length - 7 }} more language{{ "" if s.languages|length - 7 == 1 else "s" }}
        below {{ "%.1f%%"|format(s.languages[6][1] * 100) }} each.</p>
      {% endif %}
      {% else %}
      <p class="t13 muted">Not measured. Language identification needs
      <code>pip install 'dropoutt[lid]'</code>.</p>
      {% endif %}
    </div>

    <div class="card">
      <h3>Structure</h3>
      {% if c.layouts %}
      <p class="t13 muted">{{ c.structured_line }}</p>
      <div class="bars">
      {% for label, share, conf in c.layouts[:5] %}
        <div class="bar">
          <span class="label">{{ label }}</span>
          <span class="track"><span class="fill h{{ loop.index0 % 7 }}" style="width:{{ "%.1f"|format(share * 100) }}%"></span></span>
          <span class="v">{{ "%.0f%%"|format(share * 100) }}</span>
        </div>
      {% endfor %}
      </div>
      {% else %}
      <p class="t13 muted">No layout could be induced from these files.</p>
      {% endif %}

      <h4 style="margin-top:var(--s-20)">Chat templates found in the text</h4>
      {% if c.templates %}
      <p class="t13 muted">These records already carry turn delimiters. A trainer
      that applies its own template on top produces a doubled format the model
      never sees at inference.</p>
      <div class="chips">
      {% for name, count, share in c.templates %}
        <span class="badge {{ 'bad' if c.template_target and name != c.template_target else 'warn' }}">{{ name }} · {{ "{:,}".format(count) }} records</span>
      {% endfor %}
      </div>
      {% if c.template_target %}
      <p class="t12 faint" style="margin-top:var(--s-8)">Your target model uses
      <b>{{ c.template_target }}</b>.</p>
      {% endif %}
      {% else %}
      <p class="t13 muted">None. No record carries the turn delimiters of a known
      chat template, which is what a trainer applying its own template expects.</p>
      {% endif %}
    </div>
  </div>

  <div class="card" style="margin-top:var(--s-12)">
    <h3>Datasets</h3>
    <div class="scroll"><table>
      <thead><tr><th>name</th><th>layout</th><th class="r">records</th>
      <th class="r">share</th><th>licence</th></tr></thead>
      <tbody>
      {% for d in datasets %}
      <tr>
        <td>{{ d.name }}</td>
        <td class="muted">{{ d.layout or "—" }}</td>
        <td class="r">{{ "{:,}".format(d.records) }}</td>
        <td class="r muted">{{ "%.1f%%"|format(100 * d.records / s.records) if s.records else "—" }}</td>
        <td>{% if d.licence %}{{ d.licence }}{% else %}<span class="badge warn">not recorded</span>{% endif %}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table></div>
    {% if overlap %}
    <h4 style="margin-top:var(--s-20)">Datasets that repeat each other</h4>
    <p class="t12 faint">Directional: the share of the first that also appears in the second.</p>
    <div class="scroll"><table>
      <thead><tr><th>from</th><th>also in</th><th class="r">share</th></tr></thead>
      <tbody>
      {% for r in overlap %}
      <tr><td>{{ r["from"] }}</td><td>{{ r["to"] }}</td>
      <td class="r">{{ "%.1f%%"|format(r["fraction"] * 100) }}</td></tr>
      {% endfor %}
      </tbody>
    </table></div>
    {% endif %}
  </div>
</section>

{# ---------------------------------------------------------------- 02 #}
<section>
  <div class="sechead"><span class="n">02</span><h2>What would go wrong</h2></div>
  <p class="secnote">Ordered by how much of your data each one touches. Nothing
  here is a prediction about model quality — these are structural facts about the
  files, and the decision about what to do with them is yours.</p>

  {% if problems %}
    {% for p in problems %}
    <article class="finding {{ 'bad' if p.is_blocking or p.would_block else ('warn' if p.severity.value == 'warning' else 'info') }}">
      <div class="ftop">
        <span class="badge {{ 'bad' if p.is_blocking or p.would_block else ('warn' if p.severity.value == 'warning' else '') }}">
          {{ "will block" if p.is_blocking else ("would block" if p.would_block else p.severity.value) }}
        </span>
        <h3>{{ p.title }}</h3>
        <span class="fid">{{ p.check_id }}</span>
      </div>
      {% if p.scale or p.cost %}
      <p class="fscale">{{ p.scale }}{% if p.cost %}<span class="sep">·</span><span class="cost">{{ p.cost }} wasted</span>{% endif %}</p>
      {% endif %}
      <p class="fdetail">{{ p.detail }}</p>
      <p class="ffix"><b>What to do</b> — {{ p.fix }}</p>
      {% if p.evidence %}
      <details>
        <summary>Show {{ p.evidence|length }} example{{ "" if p.evidence|length == 1 else "s" }} from your data</summary>
        {% for ev in p.evidence %}
        <div class="excerpt"><span class="loc">{{ ev.source_file }}:{{ ev.source_index }}</span>{{ ev.excerpt }}</div>
        {% if ev.partner_excerpt %}
        <div class="excerpt"><span class="loc">matches{% if ev.score %} · {{ "%.0f%%"|format(ev.score * 100) }} alike{% endif %}</span>{{ ev.partner_excerpt }}</div>
        {% endif %}
        {% endfor %}
      </details>
      {% endif %}
    </article>
    {% endfor %}
  {% else %}
    <div class="allclear"><b>Nothing to fix.</b> Every check that could run came
    back clean. The list of checks that could not run is at the bottom of this page.</div>
  {% endif %}
</section>

{# ---------------------------------------------------------------- 03 #}
{% if budget %}
<section>
  <div class="sechead"><span class="n">03</span><h2>What it costs to tokenize</h2></div>
  <p class="secnote">{% if has_tokenizer %}Counted exactly, with your model's own
  tokenizer.{% else %}No <code>--model</code> was given, so the corpus is priced
  under five common tokenizers instead. The same text costs different numbers of
  tokens under different families, and for non-English data the gap is
  large.{% endif %}</p>

  <div class="card">
    <div class="scroll"><table>
      <thead><tr><th>tokenizer</th><th class="r">total tokens</th>
      <th class="r">± sampling</th><th class="r">vs cheapest</th></tr></thead>
      <tbody>
      {% for e in budget %}
      <tr>
        <td>{{ e.name }}{% if loop.first %} <span class="badge ok">cheapest</span>{% endif %}</td>
        <td class="r">{{ "{:,}".format(e.total) }}</td>
        <td class="r muted">{% if e.margin_share %}{{ "%.2f%%"|format(e.margin_share * 100) }}{% else %}exact{% endif %}</td>
        <td class="r">{% if e.premium > 0 %}+{{ "%.1f%%"|format(e.premium * 100) }}{% else %}—{% endif %}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table></div>
    <p class="t12 faint" style="margin-top:var(--s-16)">{{ budget_method }}</p>
    {% for note in budget_notes %}
    <p class="t12 faint">{{ note }}</p>
    {% endfor %}
  </div>
</section>
{% endif %}

{# ---------------------------------------------------------------- 04 #}
{% if s.atlas %}
<section>
  <div class="sechead"><span class="n">04</span><h2>Where your data sits</h2></div>
  {% if not s.atlas.available %}
  <p class="secnote">{{ s.atlas.unavailable_reason }}</p>
  {% else %}
  <p class="secnote">Your records were placed on a fixed map built from public
  training data — {{ s.atlas.regions_total }} neighbourhoods that sit in the same
  place in every dropoutt report ever produced. What follows is only what the map
  says with enough confidence and enough size to be worth acting on.</p>

  <div class="grid g4">
    <div class="card stat">
      <span class="k">Breadth</span>
      <span class="v">{{ s.atlas.regions_touched }}<span class="muted" style="font-size:var(--t-16)"> / {{ s.atlas.regions_total }}</span></span>
      <span class="n">places reached, as spread out as
      {{ "%.0f"|format(s.atlas.effective) }} evenly-used ones</span>
    </div>
    <div class="card stat">
      <span class="k">Shape</span>
      <span class="v" style="font-size:var(--t-20)">{{ s.atlas.shape or "—" }}</span>
      <span class="n">{% if s.atlas.concentration is not none %}{{ "%.0f%%"|format(s.atlas.concentration * 100) }} of perfectly even coverage{% endif %}</span>
    </div>
    <div class="card stat">
      <span class="k">Off the map</span>
      <span class="v">{{ "%.1f%%"|format(s.atlas.off_rate * 100) }}</span>
      <span class="n">{{ "{:,}".format(s.atlas.off_count) }} of
      {{ "{:,}".format(s.atlas.sampled) }} sampled records look like nothing in
      the reference corpus</span>
    </div>
    <div class="card stat">
      <span class="k">Placed</span>
      <span class="v">{{ "{:,}".format(s.atlas.placed) }}</span>
      <span class="n">records positioned{% if s.atlas.too_short %};
      {{ "{:,}".format(s.atlas.too_short) }} were too short to place{% endif %}</span>
    </div>
  </div>

  {% if s.atlas.insights %}
  <div class="card" style="margin-top:var(--s-12)">
    <h3>What the map says</h3>
    {% for i in s.atlas.insights %}
    <div class="insight {{ i.tone }}">
      <span class="rule"></span>
      <div>
        <h3>{{ i.headline }}</h3>
        <p>{{ i.detail }}</p>
        {% if i.evidence %}<span class="quote">“{{ i.evidence }}”</span>{% endif %}
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="card" style="margin-top:var(--s-12)">
    <h3>What the map says</h3>
    <p class="t14 muted">Nothing that clears the bar. No subject area is far
    enough from the map's own balance, and no single place holds enough of your
    data, for the difference to be worth acting on at this sample size.</p>
  </div>
  {% endif %}

  <div class="grid g2" style="margin-top:var(--s-12)">
    {% if s.atlas.places %}
    <div class="card">
      <h3>Where your data piles up</h3>
      <p class="t12 faint">Each place is named by your own record nearest its
      centre, because that is the only description of a neighbourhood that is
      true by construction. The map's own words for it are shown beneath.</p>
      <ul class="places">
      {% for pl in s.atlas.places %}
        <li>
          <span class="pct">{{ "%.1f%%"|format(pl.share * 100) }}</span>
          <span>
            {% if pl.yours %}<span class="yours">“{{ pl.yours }}”</span>
            {% else %}<span class="yours muted">{{ "{:,}".format(pl.records) }} records</span>{% endif %}
            <span class="cap">{% if pl.area %}{{ pl.area }}{% endif %}{% if pl.caption %} · {{ pl.caption }}{% endif %}</span>
            {% if pl.repetitive %}<span class="flag">records here are {{ "%.2f"|format(pl.cohesion) }} alike — likely one template</span>{% endif %}
          </span>
        </li>
      {% endfor %}
      </ul>
    </div>
    {% endif %}

    {% if s.atlas.thin_places %}
    <div class="card">
      <h3>Where you have only a toehold</h3>
      <p class="t12 faint">The sparsest places you reach. Each holds under 0.5%
      of your data, so they count towards breadth without contributing coverage.</p>
      <ul class="places">
      {% for pl in s.atlas.thin_places %}
        <li>
          <span class="pct">{{ "{:,}".format(pl.records) }}</span>
          <span>
            {% if pl.yours %}<span class="yours">“{{ pl.yours }}”</span>
            {% else %}<span class="yours muted">record{{ "" if pl.records == 1 else "s" }} here</span>{% endif %}
            <span class="cap">{% if pl.area %}{{ pl.area }}{% endif %}{% if pl.caption %} · {{ pl.caption }}{% endif %}</span>
          </span>
        </li>
      {% endfor %}
      </ul>
    </div>
    {% endif %}
  </div>

  {% if s.atlas.categories %}
  <div class="card" style="margin-top:var(--s-12)">
    <h3>Subjects you cover, against the map's own balance</h3>
    <p class="t12 faint">The bar is your share of placed records. The tick is how
    much of itself the map spends on that subject — the number of neighbourhoods
    it gave the area when it was built, which is the closest thing the artifact
    carries to how common the subject was in the reference corpus. The subject
    names are the atlas's L1 region labels — human captions for the coarse
    clusters on the map. Read them as approximate geography, not a classifier
    verdict on each record.</p>
    <div class="bars">
    {% for cat in s.atlas.categories %}
      <div class="bar">
        <span class="label">{{ cat.name }}</span>
        <span class="track">
          <span class="fill h{{ cat.hue }}" style="width:{{ "%.1f"|format(cat.share * 100) }}%"></span>
          {% if cat.map_share %}<span class="ref" style="left:{{ "%.1f"|format(cat.map_share * 100) }}%" title="the map spends {{ "%.0f%%"|format(cat.map_share * 100) }} of itself here"></span>{% endif %}
        </span>
        <span class="v">{{ "%.0f%%"|format(cat.share * 100) }}</span>
      </div>
    {% endfor %}
    </div>
    {% if s.atlas.gaps_line %}
    <p class="t13 muted" style="margin-top:var(--s-20)">{{ s.atlas.gaps_line }}</p>
    {% if s.atlas.gaps %}
    <div class="chips">{% for g in s.atlas.gaps %}<span class="badge">{{ g.name }}</span>{% endfor %}</div>
    {% endif %}
    {% endif %}
  </div>
  {% endif %}

  {% if s.atlas.off_count %}
  <details class="card" style="margin-top:var(--s-12)">
    <summary>Why {{ "{:,}".format(s.atlas.off_count) }} records could not be placed</summary>
    <p class="t14 muted" style="margin-top:var(--s-12)">{{ s.atlas.off_line }}</p>
    <div class="scroll"><table><tbody>
      {% if off.length %}<tr><td class="muted">Length</td><td>off-map median {{ off.length.off_median_chars }} characters, placed median {{ off.length.placed_median_chars }}</td></tr>{% endif %}
      {% if off.surface and off.surface.placed_whitespace is not none %}<tr><td class="muted">Surface</td><td>{{ "%.0f%%"|format(off.surface.off_whitespace * 100) }} whitespace and {{ "%.0f%%"|format(off.surface.off_non_letter * 100) }} non-letter, against {{ "%.0f%%"|format(off.surface.placed_whitespace * 100) }} and {{ "%.0f%%"|format(off.surface.placed_non_letter * 100) }} for placed records</td></tr>{% endif %}
      {% if off.score %}<tr><td class="muted">Distance</td><td>median similarity {{ "%.2f"|format(off.score.off_median) }} against a cutoff of {{ "%.2f"|format(off.score.cutoff) }}{% if off.score.near_miss_share %}; {{ "%.0f%%"|format(off.score.near_miss_share * 100) }} were near misses{% endif %}</td></tr>{% endif %}
      {% for name, st in off_by_dataset %}<tr><td class="muted">{{ name }}</td><td>{{ "%.0f%%"|format(st.rate * 100) }} of its records ({{ "{:,}".format(st.off_atlas) }} of {{ "{:,}".format(st.records) }})</td></tr>{% endfor %}
    </tbody></table></div>
    {% if off_examples %}
    <h4 style="margin-top:var(--s-16)">Furthest from the map</h4>
    {% for ex in off_examples %}
    <div class="excerpt"><span class="loc">similarity {{ "%.2f"|format(ex.score) }}</span>{{ ex.excerpt }}</div>
    {% endfor %}
    {% endif %}
  </details>
  {% endif %}
  {% endif %}
</section>
{% endif %}

{# ---------------------------------------------------------------- 05 #}
{% if notes %}
<section>
  <div class="sechead"><span class="n">05</span><h2>Worth knowing</h2></div>
  <p class="secnote">Measured, not wrong. These describe the corpus rather than fault it.</p>
  {% for p in notes %}
  <article class="finding info">
    <div class="ftop"><span class="badge">note</span><h3>{{ p.title }}</h3>
    <span class="fid">{{ p.check_id }}</span></div>
    <p class="fdetail">{{ p.detail }}</p>
  </article>
  {% endfor %}
</section>
{% endif %}

{# ---------------------------------------------------------------- 06 #}
<section>
  <div class="sechead"><span class="n">{{ "06" if notes else "05" }}</span><h2>The small print</h2></div>
  <div class="card">
  {% if skipped %}
  <details open>
    <summary>{{ skipped|length }} check{{ "" if skipped|length == 1 else "s" }} could not run, and what would unlock each</summary>
    <div class="scroll"><table>
    <thead><tr><th>check</th><th>why not</th><th>unlock</th></tr></thead>
    <tbody>
    {% for sk in skipped %}
    <tr><td>{{ sk.title }}<br><span class="t11 faint mono">{{ sk.check_id }}</span></td>
    <td class="muted">{{ sk.reason }}</td><td><code>{{ sk.unlock }}</code></td></tr>
    {% endfor %}
    </tbody></table></div>
  </details>
  {% endif %}
  {% if degradations %}
  <details>
    <summary>{{ degradations|length }} thing{{ "" if degradations|length == 1 else "s" }} fell back rather than failing</summary>
    <ul class="muted t13" style="margin:var(--s-8) 0 0 var(--s-20)">{% for d in degradations %}<li>{{ d }}</li>{% endfor %}</ul>
  </details>
  {% endif %}
  <details>
    <summary>How to reproduce this scan</summary>
    <div class="scroll"><table><tbody>
    {% for k, v in provenance %}
    <tr><td class="muted">{{ k }}</td><td class="mono">{{ v }}</td></tr>
    {% endfor %}
    </tbody></table></div>
  </details>
  </div>
</section>

<footer>
  <p>dropoutt {{ pipeline_version }} · fingerprint {{ fingerprint_id }} ·
  {{ "{:,}".format(s.records) }} records in {{ "%.1f"|format(s.elapsed) }}s{% if shards > 1 %} across {{ shards }} shards{% endif %}.
  {% if not s.blocking_enabled %}No pass-or-fail verdict was issued because no
  target was declared — pass <code>--target sft</code> to turn findings into an
  exit code.{% endif %}</p>
  <p>Findings are structural observations about the files. No measured effect on
  model quality is attached to acting on any of them.</p>
  <p>{% if includes_evidence %}This file quotes your data, including anything sensitive the scan
  found. Personal data matched by the PII check is masked; surrounding text is not. Re-run with
  <code>--no-evidence</code> before sharing it outside the dataset's trust boundary.
  {% else %}Record excerpts and source locations were omitted with <code>--no-evidence</code>.
  Aggregate numbers, dataset names and the scan root remain.{% endif %}</p>
</footer>
</div>
"""


def _tokens_short(count: int | None) -> str:
    if not count:
        return "—"
    if count >= 1_000_000_000:
        return f"{count / 1e9:.1f}B"
    if count >= 1_000_000:
        return f"{count / 1e6:.1f}M"
    if count >= 1_000:
        return f"{count / 1e3:.0f}k"
    return f"{count:,}"


def render(
    result: ScanResult,
    fp: Fingerprint,
    budget: Any = None,
    *,
    include_evidence: bool = True,
    summary: ScanSummary | None = None,
) -> str:
    env = Environment(autoescape=True, undefined=StrictUndefined,
                      trim_blocks=True, lstrip_blocks=True)
    template = env.from_string(_TEMPLATE)
    s = summary or build(result, budget=budget, include_evidence=include_evidence)

    for problem in (*s.problems, *s.notes):
        for ev in problem.evidence:
            ev.excerpt = safe_snippet(ev.excerpt)
            if ev.partner_excerpt:
                ev.partner_excerpt = safe_snippet(ev.partner_excerpt)

    overlap: list[dict] = []
    for problem in s.problems + s.notes:
        if problem.check_id == "T1-OVERLAP-001":
            for finding in result.findings:
                if finding.check_id == "T1-OVERLAP-001":
                    overlap = finding.data.get("matrix", [])[:20]

    seen: set[str] = set()
    skipped = []
    for entry in result.skipped:
        if entry.reason in seen:
            continue
        seen.add(entry.reason)
        skipped.append(entry)

    off = (s.atlas.off_detail if s.atlas else {}) or {}
    off_examples = []
    if include_evidence and s.atlas:
        for ex in s.atlas.off_examples[:4]:
            off_examples.append({
                "score": float(ex.get("score", 0.0)),
                "excerpt": safe_snippet(
                    str(ex.get("excerpt", "")).replace("\n", " "), 160
                ),
            })

    has_tokenizer = result.ctx.tokenizer is not None
    token_note = ""
    if s.tokens:
        token_note = "counted exactly" if has_tokenizer else (
            f"estimated, ±{s.token_margin * 100:.2f}%" if s.token_margin
            else "estimated from a sample"
        )

    root = result.ctx.root
    return template.render(
        css=stylesheet(),
        logo=LOGO_SVG,
        s=s,
        c=s.composition,
        problems=s.problems,
        notes=s.notes,
        root=root,
        root_short=root.rstrip("/").split("/")[-1] or root,
        tokens_short=_tokens_short(s.tokens),
        token_note=token_note,
        datasets=fp.datasets,
        overlap=overlap,
        budget=budget_rows(budget),
        budget_method=budget_method(budget, exact=has_tokenizer),
        budget_notes=list(getattr(budget, "notes", []) or []),
        has_tokenizer=has_tokenizer,
        skipped=skipped,
        degradations=result.ctx.degradations,
        provenance=sorted(fp.provenance.items()),
        fingerprint_id=fp.fingerprint_id,
        pipeline_version=fp.pipeline_version,
        includes_evidence=include_evidence,
        shards=int(result.ctx.stats.get("shards", 1) or 1),
        off=off,
        off_by_dataset=sorted(
            ((k, v) for k, v in (off.get("by_dataset") or {}).items()),
            key=lambda kv: -kv[1]["rate"],
        )[:4],
        off_examples=off_examples,
    )
