"""Self-contained HTML report.

One file, no network, no CDN, no web fonts, opens from ``file://``. That matters
because the users this was built for work on clusters where standing up a server
and forwarding a port is awkward: a single file can be produced inside a batch
job and copied with ``scp`` when policy permits. By default it contains record
excerpts; ``--no-evidence`` removes excerpts and source locations.

Autoescaping is on unconditionally and every corpus string additionally passes
through :func:`safe_snippet`, because everything rendered here came from data we
did not write.

**The page describes before it complains.** It used to open with a list of
findings, which meant a reader who had just been handed a folder learned what
was wrong with it before learning what it was — and learned what it was only by
inference, since a finding mentions a property of the corpus exactly when that
property is broken. So composition comes first: what language, what shape,
whether it is already formatted, how big.

Then the findings, then the token budget, then the map. That order is what a
person actually asks in sequence: what is this, what is wrong with it, what will
it cost, and what is it missing. The one-line verdict sits at the head of the
findings rather than at the head of the page: the sentence it carries is a count
of what is directly below it and a name for the worst of them, which is a
caption for that list and was a verdict on a corpus the reader had not been
shown yet.

Both pages open the same way: the folder's name as the title, one sentence
saying what the corpus is, and links to the sections. The atlas page then puts
the four coverage numbers first and the map second. The map draws the fifteen
subject areas holding most of the corpus in full — the same cut the Markdown
twin makes — and folds the rest, and the areas never reached, under a line that
says how many there are. Every one of the map's cells is still in the file, so
a search finds it and the reading key above the map applies to all of them.
The words are the Markdown file's words — subject areas, subregions, the map —
so a reader moving between the two is not asked to learn a second vocabulary.

What the page must not do is present the atlas's own labels as facts about the
data. See :mod:`dropoutt.report.summary` for why, and for the rule that a place
on the map is named by the reader's own record before it is named by a caption.

The density grid and coverage chart work without scripts. The grid
has no sort control and no tooltips — every cell prints its own ratio, which is
also what makes it survive a printer and a screenshot. See
:func:`dropoutt.report.atlas_story._grid`.
"""

from __future__ import annotations

from typing import Any

from jinja2 import Environment, StrictUndefined

from ..fingerprint import Fingerprint
from ..models import PIPELINE_VERSION
from ..runner import ScanResult
from .atlas_story import (
    DENSITY_DEFINITION,
    IMBALANCE_CAPTION,
    REACH_DEFINITION,
    density_ratio,
    format_reach,
)
from .escaping import safe_snippet
from .markdown import GRID_ROWS
from .payload import atlas_identity, off_map_examples, overlap_matrix, skipped_checks, token_note
from .summary import ScanSummary, budget_method, budget_rows, build
from .theme import TEXT_LOGO_SVG, gradient, stylesheet

_TEMPLATE_HEAD = """<!-- generated by dropoutt {{ pipeline_version }} -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy"
      content="default-src 'none'; style-src 'unsafe-inline'; img-src data:">
<title>dropoutt — {{ root_short }}</title>
<style>{{ css|safe }}</style>
<div class="wrap">

<header class="masthead">
  <div class="brand">
    <span class="kind">dataset report</span>
    {{ logo|safe }}
  </div>
  <span class="where">{{ root }}</span>
</header>

<section class="report-intro" aria-labelledby="intro-title">
  <h1 id="intro-title">{{ root_short }}</h1>
  <p class="lede"><b>{{ "{:,}".format(s.records) }}</b> records in
    {{ s.datasets }} dataset{{ "" if s.datasets == 1 else "s" }} and
    {{ s.files }} file{{ "" if s.files == 1 else "s" }}{% if s.language_line %};
    {{ s.language_line }}{% endif %}.{% if s.tokens %} About {{ tokens_short }} tokens.{% endif %}</p>
  <nav class="report-nav" aria-label="Report sections">
    <a href="#corpus"><span class="n">{{ sec.corpus }}</span>What this corpus is</a>
    <a href="#problems"><span class="n">{{ sec.problems }}</span>What would go wrong</a>
    {% if budget %}<a href="#budget"><span class="n">{{ sec.budget }}</span>What it costs to tokenize</a>{% endif %}
    {% if s.atlas %}<a href="#atlas"><span class="n">{{ sec.atlas }}</span>Where your data sits</a>{% endif %}
    {% if notes %}<a href="#notes"><span class="n">{{ sec.notes }}</span>Worth knowing</a>{% endif %}
    <a href="#small-print"><span class="n">{{ sec.small_print }}</span>The small print</a>
  </nav>
</section>

{# ---------------------------------------------------------------- 01 #}
<section id="corpus">
  <div class="sechead"><h2><span class="n">{{ sec.corpus }}</span> What this corpus is</h2></div>

  <div class="grid g4">
    <div class="card stat">
      <span class="k">Records</span>
      <span class="v">{{ "{:,}".format(s.records) }}</span>
      <span class="n">{{ s.datasets }} dataset{{ "" if s.datasets == 1 else "s" }}
        in {{ s.files }} file{{ "" if s.files == 1 else "s" }}</span>
    </div>
    <div class="card stat">
      <span class="k">Tokens</span>
      <span class="v">{{ tokens_short }}</span>
      <span class="n">{% if s.tokens %}{{ token_note }}{% else %}no tokenizer available{% endif %}</span>
    </div>
    <div class="card stat">
      <span class="k">Average record</span>
      <span class="v">{{ "{:,}".format(c.mean_chars) }}<small> chars</small></span>
    </div>
  </div>

  <div class="grid g2">
    <div class="card">
      <h3>Languages</h3>
      {% if s.languages %}
      <div class="bars">
      {% for code, share in languages_shown %}
        <div class="bar">
          <span class="label">{{ code }}</span>
          <span class="track"><span class="fill" style="width:{{ "%.1f"|format(share * 100) }}%"></span></span>
          <span class="v">{{ "%.1f%%"|format(share * 100) if share >= 0.001 else "<0.1%" }}</span>
        </div>
      {% endfor %}
      </div>
      {% if s.languages|length > languages_shown|length %}
      <p class="t12 faint" style="margin-top:var(--s-12)">and
        {{ s.languages|length - languages_shown|length }} more
        language{{ "" if s.languages|length - languages_shown|length == 1 else "s" }},
        each under {{ "%.1f%%"|format(languages_shown[-1][1] * 100) if languages_shown[-1][1] >= 0.001 else "0.1%" }}.</p>
      {% endif %}
      {% else %}
      <p class="desc">Not measured. Language identification needs a
      working install — run <code>pip install --force-reinstall dropoutt</code>.</p>
      {% endif %}
    </div>

    <div class="card">
      <h3>Structure</h3>
      {% if c.layouts %}
      {% if c.structured_line %}<p class="desc">{{ c.structured_line }}</p>{% endif %}
      <div class="bars">
      {% for label, share, conf in c.layouts[:5] %}
        <div class="bar">
          <span class="label">{{ label }}</span>
          <span class="track"><span class="fill" style="width:{{ "%.1f"|format(share * 100) }}%"></span></span>
          <span class="v">{{ "%.0f%%"|format(share * 100) }}</span>
        </div>
      {% endfor %}
      </div>
      {% else %}
      <p class="desc">No layout could be induced from these files.</p>
      {% endif %}

      {# A clean result here is the expected one, and saying so took four lines
         to report the absence of a problem the reader never had. It appears
         only when a template was actually found in the text. #}
      {% if c.templates %}
      <h4 style="margin-top:var(--s-20)">Chat templates found in the text</h4>
      <p class="desc">These records already carry turn delimiters. A trainer
      that applies its own template on top produces a doubled format the model
      never sees at inference.</p>
      <div class="chips">
      {% for name, count, share in c.templates %}
        <span class="badge {{ 'bad' if c.template_target and name != c.template_target else 'warn' }}">{{ name }} · {{ "{:,}".format(count) }} records</span>
      {% endfor %}
      </div>
      {% if c.template_target %}
      <p class="t12 faint" style="margin-top:var(--s-8)">Your target model uses
      <b>{{ c.template_target }}</b>.</p>
      {% endif %}
      {% endif %}
    </div>
  </div>

  <div class="card">
    <h3>Datasets</h3>
    <div class="scroll"><table>
      <thead><tr><th>Name</th><th>Layout</th><th class="r">Records</th>
      <th class="r">Share</th><th>Licence</th></tr></thead>
      <tbody>
      {% for d in datasets %}
      <tr>
        <td>{{ d.name }}</td>
        <td class="muted">{{ d.layout or "—" }}</td>
        <td class="r">{{ "{:,}".format(d.records) }}</td>
        <td class="r muted">{{ "%.1f%%"|format(100 * d.records / s.records) if s.records else "—" }}</td>
        <td>{% if d.licence %}{{ d.licence }}{% else %}<span class="badge warn">not recorded</span>{% endif %}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table></div>
  </div>

  {% if overlap %}
  <div class="card">
    <h3>Datasets that repeat each other</h3>
    <p class="desc">Directional: the share of the first that also appears
    in the second.</p>
    <div class="scroll"><table>
      <thead><tr><th>From</th><th>Also in</th><th class="r">Share</th></tr></thead>
      <tbody>
      {% for r in overlap %}
      <tr><td>{{ r["from"] }}</td><td>{{ r["to"] }}</td>
      <td class="r">{{ "%.1f%%"|format(r["fraction"] * 100) }}</td></tr>
      {% endfor %}
      </tbody>
    </table></div>
  </div>
  {% endif %}
</section>

{# ---------------------------------------------------------------- 02 #}
<section id="problems">
  <div class="sechead"><h2><span class="n">{{ sec.problems }}</span> What would go wrong</h2></div>

  <div class="verdict {{ s.tone }}">
    <span class="dot"></span>
    <span class="headline">{{ s.verdict }}</span>
    {% if s.subtitle %}<span class="lead">{{ s.subtitle }}</span>{% endif %}
  </div>

  {% if problems %}
    {% for p in problems %}
    <article class="finding {{ 'bad' if p.is_blocking or p.would_block else ('warn' if p.severity.value == 'warning' else 'info') }}">
      <div class="ftop">
        <span class="badge {{ 'bad' if p.is_blocking or p.would_block else ('warn' if p.severity.value == 'warning' else '') }}">
          {{ "will block" if p.is_blocking else ("would block" if p.would_block else p.severity.value) }}
        </span>
        <h3>{{ p.title }}</h3>
        <span class="fid">{{ p.check_id }}</span>
      </div>
      {% if p.scale or p.cost %}
      <p class="fscale">{{ p.scale }}{% if p.cost %}<span class="sep">·</span><span class="cost">{{ p.cost }} wasted</span>{% endif %}</p>
      {% endif %}
      <p class="fdetail">{{ p.detail }}</p>
      <p class="ffix"><b>What to do</b> — {{ p.fix }}</p>
      {% if p.evidence %}
      <details>
        <summary>Show {{ p.evidence|length }} example{{ "" if p.evidence|length == 1 else "s" }} from your data</summary>
        {% for ev in p.evidence %}
        <div class="excerpt"><span class="loc">{{ ev.source_file }}:{{ ev.source_index }}</span>{{ ev.excerpt }}</div>
        {% if ev.partner_excerpt %}
        <div class="excerpt"><span class="loc">matches{% if ev.score %} · {{ "%.0f%%"|format(ev.score * 100) }} alike{% endif %}</span>{{ ev.partner_excerpt }}</div>
        {% endif %}
        {% endfor %}
      </details>
      {% endif %}
    </article>
    {% endfor %}
  {% else %}
    <div class="allclear"><b>Nothing to fix.</b> Every check that could run came
    back clean. The list of checks that could not run is at the bottom of this page.</div>
  {% endif %}
</section>

{# ---------------------------------------------------------------- 03 #}
{% if budget %}
<section id="budget">
  <div class="sechead"><h2><span class="n">{{ sec.budget }}</span> What it costs to tokenize</h2></div>

  <div class="card">
    <div class="scroll"><table>
      <thead><tr><th>Tokenizer</th><th class="r">Total tokens</th>
      <th class="r">± sampling</th><th class="r">vs cheapest</th></tr></thead>
      <tbody>
      {% for e in budget %}
      <tr>
        <td>{{ e.name }}{% if loop.first %} <span class="badge ok">cheapest</span>{% endif %}</td>
        <td class="r">{{ "{:,}".format(e.total) }}</td>
        <td class="r muted">{% if e.margin_share %}{{ "%.2f%%"|format(e.margin_share * 100) }}{% else %}exact{% endif %}</td>
        <td class="r">{% if e.premium > 0 %}+{{ "%.1f%%"|format(e.premium * 100) }}{% else %}—{% endif %}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table></div>
    <p class="t12 faint" style="margin-top:var(--s-16)">{{ budget_method }}</p>
    {% for note in budget_notes %}
    <p class="t12 faint">{{ note }}</p>
    {% endfor %}
  </div>
</section>
{% endif %}

"""


#: The map, as the scan report's section 04 and as the whole of an atlas page.
#: Held apart from the surrounding template so `dropoutt atlas` renders the
#: same markup a scan does rather than a second version of it that drifts.

_ATLAS_SECTION = """{# ---------------------------------------------------------------- 04 #}
{# One subject area of the map: its name, how much of the corpus it holds, its
   reach, and every subregion inside it, densest first. #}
{% macro topic(a) %}
      <section id="topic-{{ a.area }}" class="amap-area">
        <div class="topic-heading">
          <div>
            <h4 class="aname" id="topic-name-{{ a.area }}">{{ a.name }}</h4>
            <p class="ameta">
              <span>{{ "{:,}".format(a.records) }} record{{ "" if a.records == 1 else "s" }}</span>
              <span>{{ "%.1f%%"|format(a.share * 100) if a.share >= 0.001 else ("<0.1%" if a.records else "0%") }} of placed</span>
            </p>
          </div>
          <div class="topic-reach">
            <span class="coverage-value"><b>{{ format_reach(a.effective_reach) }}</b> / {{ a.cells|length }} reach</span>
            <span class="coverage-track" role="meter" aria-labelledby="topic-name-{{ a.area }}"
                  aria-valuemin="0" aria-valuemax="100"
                  aria-valuenow="{{ '%.2f'|format(100 * a.effective_reach / a.cells|length if a.cells else 0) }}"
                  aria-valuetext="reach {{ format_reach(a.effective_reach) }} of {{ a.cells|length }} subregions, summing min(1, density) over each">
              <span style="width:{{ '%.2f'|format(100 * a.effective_reach / a.cells|length if a.cells else 0) }}%"></span>
            </span>
          </div>
        </div>
        <table class="topic-table" aria-labelledby="topic-name-{{ a.area }}">
          <thead><tr><th scope="col">Subregion</th><th scope="col" class="r">vs the map</th></tr></thead>
          <tbody>
          {% for cell in a.cells %}
            <tr class="acell d{{ cell.step }}{% if cell.records %} on{% endif %}">
              <td><span class="cn">{{ cell.caption or "Subregion " ~ cell.region }}</span></td>
              <td class="r"><span class="cell">{{ cell.label }}</span><span class="sr-only">, {{ cell.described }}</span></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </section>
{% endmacro %}
{% if s.atlas %}
<section id="atlas">
  <div class="sechead"><h2><span class="n">{{ atlas_no }}</span> {{ atlas_title }}</h2></div>
  {% if not s.atlas.available %}
  <p class="t14 muted">{{ s.atlas.unavailable_reason }}</p>
  {% else %}

  <div id="coverage-overview" class="grid g4">
    <div class="card stat">
      <span class="k">Reach</span>
      <span class="v">{{ format_reach(s.atlas.effective) }}<small> / {{ "{:,}".format(s.atlas.regions_total) }}</small></span>
      <span class="n">subregions, summing min(1, density) over each; records
      were found in {{ "{:,}".format(s.atlas.regions_touched) }}</span>
    </div>
    <div class="card stat">
      <span class="k">Shape</span>
      <span class="v">{{ s.atlas.shape or "—" }}</span>
      <span class="n">{% if s.atlas.concentration is not none %}{{ "%.0f%%"|format(s.atlas.concentration * 100) }} of perfectly even coverage{% endif %}</span>
    </div>
    <div class="card stat">
      <span class="k">Off the map</span>
      <span class="v">{{ "%.1f%%"|format(s.atlas.off_rate * 100) }}</span>
      <span class="n">{{ "{:,}".format(s.atlas.off_count) }} of
      {{ "{:,}".format(s.atlas.sampled) }} sampled records were not similar
      enough to the map to place</span>
    </div>
    <div class="card stat">
      <span class="k">Placed</span>
      <span class="v">{{ s.atlas.placed_label }}</span>
      <span class="n">{{ s.atlas.placed_note }}</span>
    </div>
  </div>

  {% if s.atlas.grid %}
  {% set reached = s.atlas.grid|selectattr("records")|list %}
  {% set unreached = s.atlas.grid|rejectattr("records")|list %}
  <div class="card">
    <h3 id="topic-details">Subject areas</h3>
    <p class="desc">One block per subject area your data reached, the areas
    holding most of your records first. Inside each, subregions are listed
    densest first. Record counts are estimates when only part of your data was
    checked.</p>

    <div class="key">
      <div class="legend">
        <span class="ramp" style="background:{{ gradient }}"></span>
        <span class="ends">
          <span>no reach</span>
          <span class="mid">as common as on the map</span>
          <span>over-represented, up to {{ ratio(s.atlas.grid_peak) }}</span>
        </span>
      </div>
      <p>{{ density_definition }} 2&times; is twice as common as on the map;
      0 means none was found in the sample.</p>
      <p>{{ reach_definition }} 15 / 16 means the sum falls one short of the
      area&rsquo;s subregions: extra records in one subregion do not fill a
      gap in another.</p>
      <p>Names describe the reference text, not your records. The records
      quoted beside them are your own, and are what the names stand for
      here.</p>
    </div>

    <div class="amap">
    {% for a in reached[:grid_rows] %}{{ topic(a) }}{% endfor %}
    </div>

    {% if reached|length > grid_rows %}
    <details class="more">
      <summary>{{ "{:,}".format(reached|length - grid_rows) }} further subject
        area{{ "" if reached|length - grid_rows == 1 else "s" }} reached
        <span class="muted">— each holding
        {{ "%.1f%%"|format(reached[grid_rows].share * 100) if reached[grid_rows].share >= 0.001 else "under 0.1%" }}
        of your placed records or less</span></summary>
      <div class="amap">
      {% for a in reached[grid_rows:] %}{{ topic(a) }}{% endfor %}
      </div>
    </details>
    {% endif %}

    {% if unreached %}
    <details class="more">
      <summary>{{ "{:,}".format(unreached|length) }} of the map&rsquo;s
        {{ "{:,}".format(s.atlas.grid|length) }} subject areas never reached
        <span class="muted">— no sampled record landed in any of their
        subregions</span></summary>
      <div class="amap">
      {% for a in unreached %}{{ topic(a) }}{% endfor %}
      </div>
    </details>
    {% endif %}
  </div>
  {% endif %}

  <div class="card">
    <h3 id="atlas-comparisons">Notable differences from the reference</h3>
    {% if s.atlas.insights %}
    <p class="desc">Differences large enough, with enough records behind them,
    to stand out from normal sample variation. The largest come first.</p>
    <ul class="insights">
    {% for i in s.atlas.insights %}
      <li class="insight {{ i.tone }}">
        <span class="rule"></span>
        <div>
          <span class="badge {{ 'warn' if i.tone == 'warn' else 'info' }}">{{ i.label }}</span>
          <p class="ihead">{{ i.headline }}</p>
          <p>{{ i.detail }}</p>
          {% if i.evidence %}<span class="quote">“{{ i.evidence }}”</span>{% endif %}
        </div>
      </li>
    {% endfor %}
    </ul>
    {% else %}
    <p class="desc">This sample did not show differences large and clear enough
    to highlight. A larger sample may reveal more.</p>
    {% endif %}
  </div>

  <div class="grid g2">
    {% if s.atlas.places %}
    <div class="card">
      <h3>What you have most of, against the map</h3>
      <ul class="places">
      {% for pl in s.atlas.places %}
        <li>
          <span class="pct">{{ ratio(pl.ratio) }}</span>
          <span>
            {% if pl.yours %}<span class="yours">“{{ pl.yours }}”</span>
            {% else %}<span class="yours muted">{{ "{:,}".format(pl.records) }} records</span>{% endif %}
            <span class="cap">{% if pl.area %}{{ pl.area }} · {% endif %}{{ "%.1f%%"|format(pl.share * 100) }} of your placed records</span>
            {% if pl.repetitive %}<span class="flag">records here are {{ "%.2f"|format(pl.cohesion) }} alike — likely one template</span>{% endif %}
          </span>
        </li>
      {% endfor %}
      </ul>
    </div>
    {% endif %}

    {% if s.atlas.thin_places %}
    <div class="card">
      <h3>What you have least of, against the map</h3>
      <ul class="places">
      {% for pl in s.atlas.thin_places %}
        <li>
          <span class="pct">{{ ratio(pl.ratio) }}</span>
          <span>
            {% if pl.yours %}<span class="yours">“{{ pl.yours }}”</span>
            {% else %}<span class="yours muted">{{ "{:,}".format(pl.records) }} records</span>{% endif %}
            <span class="cap">{% if pl.area %}{{ pl.area }} · {% endif %}{{ "%.1f%%"|format(pl.share * 100) }} of your placed records</span>
          </span>
        </li>
      {% endfor %}
      </ul>
    </div>
    {% endif %}
  </div>

  {% if s.atlas.imbalances %}
  <div class="card">
    <h3>Where you are farthest from the map</h3>
    <p class="desc">{{ imbalance_caption }}</p>
    <ul class="imbalances">
    {% for item in s.atlas.imbalances %}
      <li>
        <span class="pct {{ item.direction }}">{{ ratio(item.ratio) }}</span>
        <span>
          {# The badge names the direction once; the caption does not repeat it. #}
          <span class="badge">{{ item.direction }}</span>
          {% if item.yours %}<span class="yours">“{{ item.yours }}”</span>
          {% elif item.records %}<span class="yours muted">{{ "{:,}".format(item.records) }} records</span>
          {% else %}<span class="yours muted">no record of yours landed here</span>{% endif %}
          <span class="cap">{% if item.area %}{{ item.area }}{% endif %}{% if item.records %}{% if item.area %} · {% endif %}{{ "%.1f%%"|format(item.share * 100) }} of your placed records{% endif %}</span>
        </span>
      </li>
    {% endfor %}
    </ul>
  </div>
  {% endif %}

  {# The subject bar chart that stood here said the same thing as the grid
     above, one level coarser and without the map's own resolution beside it.
     Its one irreplaceable line — how much of the map this corpus never touches
     — is a caption on the grid instead. #}

  {% if s.atlas.off_count %}
  <details class="card" id="off-map">
    <summary>Why {{ "{:,}".format(s.atlas.off_count) }} records could not be placed</summary>
    <p class="desc">{{ s.atlas.off_line }}</p>
    <div class="scroll"><table><tbody>
      {% if off.length %}<tr><td class="muted">Length</td><td>off-map median {{ off.length.off_median_chars }} characters, placed median {{ off.length.placed_median_chars }}</td></tr>{% endif %}
      {% if off.surface and off.surface.placed_whitespace is not none %}<tr><td class="muted">Surface</td><td>{{ "%.0f%%"|format(off.surface.off_whitespace * 100) }} whitespace and {{ "%.0f%%"|format(off.surface.off_non_letter * 100) }} non-letter, against {{ "%.0f%%"|format(off.surface.placed_whitespace * 100) }} and {{ "%.0f%%"|format(off.surface.placed_non_letter * 100) }} for placed records</td></tr>{% endif %}
      {% if off.score %}<tr><td class="muted">Distance</td><td>median similarity {{ "%.2f"|format(off.score.off_median) }} against a cutoff of {{ "%.2f"|format(off.score.cutoff) }}{% if off.score.near_miss_share %}; {{ "%.0f%%"|format(off.score.near_miss_share * 100) }} were near misses{% endif %}</td></tr>{% endif %}
      {% for name, st in off_by_dataset %}<tr><td class="muted">{{ name }}</td><td>{{ "%.0f%%"|format(st.rate * 100) }} of its records ({{ "{:,}".format(st.off_atlas) }} of {{ "{:,}".format(st.records) }})</td></tr>{% endfor %}
    </tbody></table></div>
    {% if off_examples %}
    <h4 style="margin-top:var(--s-16)">Furthest from the map</h4>
    {% for ex in off_examples %}
    <div class="excerpt"><span class="loc">similarity {{ "%.2f"|format(ex.score) }}</span>{{ ex.excerpt }}</div>
    {% endfor %}
    {% endif %}
  </details>
  {% endif %}
  {% endif %}
</section>
{% endif %}

"""

_TEMPLATE_TAIL = """{# ---------------------------------------------------------------- 05 #}
{% if notes %}
<section id="notes">
  <div class="sechead"><h2><span class="n">{{ sec.notes }}</span> Worth knowing</h2></div>
  {% for p in notes %}
  <article class="finding info">
    <div class="ftop"><span class="badge">note</span><h3>{{ p.title }}</h3>
    <span class="fid">{{ p.check_id }}</span></div>
    <p class="fdetail">{{ p.detail }}</p>
  </article>
  {% endfor %}
</section>
{% endif %}

{# ---------------------------------------------------------------- 06 #}
<section id="small-print">
  <div class="sechead"><h2><span class="n">{{ sec.small_print }}</span> The small print</h2></div>
  <div class="card">
  {% if skipped %}
  <details open>
    <summary>{{ skipped|length }} check{{ "" if skipped|length == 1 else "s" }} could not run, and what would unlock each</summary>
    <div class="scroll"><table>
    <thead><tr><th>Check</th><th>Why not</th><th>Unlock</th></tr></thead>
    <tbody>
    {% for sk in skipped %}
    <tr><td>{{ sk.title }}<br><span class="t11 faint mono">{{ sk.check_id }}</span></td>
    <td class="muted">{{ sk.reason }}</td><td><code>{{ sk.unlock }}</code></td></tr>
    {% endfor %}
    </tbody></table></div>
  </details>
  {% endif %}
  {% if degradations %}
  <details>
    <summary>{{ degradations|length }} thing{{ "" if degradations|length == 1 else "s" }} fell back rather than failing</summary>
    <ul class="muted t13" style="margin:var(--s-8) 0 0 var(--s-20)">{% for d in degradations %}<li>{{ d }}</li>{% endfor %}</ul>
  </details>
  {% endif %}
  <details>
    <summary>How to reproduce this scan</summary>
    <div class="scroll"><table><tbody>
    {% for k, v in provenance %}
    <tr><td class="muted">{{ k }}</td><td class="mono">{{ v }}</td></tr>
    {% endfor %}
    </tbody></table></div>
  </details>
  </div>
</section>

<footer>
  <p>dropoutt {{ pipeline_version }} · fingerprint {{ fingerprint_id }} ·
  {{ "{:,}".format(s.records) }} records in {{ "%.1f"|format(s.elapsed) }}s{% if shards > 1 %} across {{ shards }} shards{% endif %}.
  {% if not s.blocking_enabled %}No pass-or-fail verdict was issued because no
  target was declared — pass <code>--target sft</code> to turn findings into an
  exit code.{% endif %}</p>
  <p>Findings are structural observations about the files. No measured effect on
  model quality is attached to acting on any of them.</p>
  {% if atlas_id %}<p>Subject areas and coverage were measured against
  <strong>{{ atlas_id.version }}</strong>{% if atlas_id.n_l1 %} ({{ "{:,}".format(atlas_id.n_l1) }} subject
  areas over {{ "{:,}".format(atlas_id.n_regions or 0) }} cells){% endif %}, encoder
  <code>{{ atlas_id.embed_model }}</code>{% if atlas_id.normalization_variant %},
  {{ atlas_id.normalization_variant }} normalization{% endif %}.
  Pipeline <code>{{ atlas_id.pipeline_hash[:12] }}</code>, encoder weights
  <code>{{ atlas_id.encoder_weight_hash[:12] }}</code>{% if atlas_id.encoder_built_with %},
  quantised from the weights the atlas was fitted on
  (<code>{{ atlas_id.encoder_built_with[:12] }}</code>){% endif %}. Coverage numbers are only
  comparable to numbers measured against the same three.</p>{% endif %}
  <p>{% if includes_evidence %}This file quotes your data, including anything sensitive the scan
  found. Personal data matched by the PII check is masked; surrounding text is not. Re-run with
  <code>--no-evidence</code> before sharing it outside the dataset's trust boundary.
  {% else %}Record excerpts and source locations were omitted with <code>--no-evidence</code>.
  Aggregate numbers, dataset names and the scan root remain.{% endif %}</p>
</footer>
</div>
"""

_TEMPLATE = _TEMPLATE_HEAD + _ATLAS_SECTION + _TEMPLATE_TAIL

#: `dropoutt atlas`, as a page. The masthead and the footer are this command's
#: own; the map between them is :data:`_ATLAS_SECTION`, the same markup a scan
#: report carries, so the two cannot describe the same geometry differently.
_ATLAS_TEMPLATE = """<!-- generated by dropoutt {{ pipeline_version }} -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy"
      content="default-src 'none'; style-src 'unsafe-inline'; img-src data:">
<title>dropoutt atlas — {{ root_short }}</title>
<style>{{ css|safe }}</style>
<div class="wrap">

<header class="masthead">
  <div class="brand">
    <span class="kind">coverage map</span>
    {{ logo|safe }}
  </div>
  <span class="where">{{ root }}</span>
</header>

<section class="report-intro" aria-labelledby="intro-title">
  <h1 id="intro-title">Where {{ root_short }} sits on the map</h1>
  {% if s.atlas and s.atlas.available %}
  <p class="lede"><b>{{ "{:,}".format(d.records) }}</b> records in
    {{ d.datasets }} dataset{{ "" if d.datasets == 1 else "s" }}{% if d.language_line %};
    {{ d.language_line }}{% if d.languages|length > 3 %} and
    {{ d.languages|length - 3 }} more{% endif %}{% endif %}{% if atlas_id %},
    measured against <b>{{ atlas_id.version }}</b>{% endif %}.
    {% if s.atlas.shape_line %}{{ s.atlas.shape_line }}{% endif %}</p>
  <nav class="report-nav" aria-label="Report sections">
    <a href="#coverage-overview">Overview</a>
    {% if s.atlas.grid %}<a href="#topic-details">Subject areas</a>{% endif %}
    <a href="#atlas-comparisons">What stands out</a>
    {% if s.atlas.off_count %}<a href="#off-map">Off the map</a>{% endif %}
    {% if findings %}<a href="#findings">What the shape means</a>{% endif %}
  </nav>
  {% else %}
  <p class="lede">The map compares sampled records with a fixed reference
  corpus to measure subject coverage. Coverage results are unavailable for
  this report.</p>
  {% endif %}
</section>

{{ atlas_body|safe }}

{% if findings %}
<section id="findings">
  <div class="sechead"><h2>What the shape means</h2></div>
  {% for f in findings %}
  <article class="finding {{ "warn" if f.severity == "warning" else "info" }}">
    <div class="ftop"><span class="badge{{ " warn" if f.severity == "warning" else "" }}">{{ f.severity }}</span><h3>{{ f.title }}</h3>
    <span class="fid">{{ f.check_id }}</span></div>
    <p class="fdetail">{{ f.detail }}</p>
    {% if f.fix %}<p class="ffix">{{ f.fix }}</p>{% endif %}
  </article>
  {% endfor %}
</section>
{% endif %}

<footer>
  <p>dropoutt {{ pipeline_version }} ·
  {{ "{:,}".format(d.records) }} records in {{ "%.1f"|format(d.elapsed_seconds) }}s{% if d.shards > 1 %} across {{ d.shards }} shards{% endif %}.
  This page is the map only — run <code>dropoutt scan</code> for the checks.</p>
  {% if d.degraded %}
  <p>{{ d.degraded|length }} thing{{ "" if d.degraded|length == 1 else "s" }} fell back rather than failing:
  {{ d.degraded|join("; ") }}.</p>
  {% endif %}
  {% if atlas_id %}<p>Subject areas and coverage were measured against
  <strong>{{ atlas_id.version }}</strong>{% if atlas_id.n_l1 %} ({{ "{:,}".format(atlas_id.n_l1) }} subject
  areas over {{ "{:,}".format(atlas_id.n_regions or 0) }} cells){% endif %}, encoder
  <code>{{ atlas_id.embed_model }}</code>{% if atlas_id.normalization_variant %},
  {{ atlas_id.normalization_variant }} normalization{% endif %}.
  Pipeline <code>{{ atlas_id.pipeline_hash[:12] }}</code>, encoder weights
  <code>{{ atlas_id.encoder_weight_hash[:12] }}</code>{% if atlas_id.encoder_built_with %},
  quantised from the weights the atlas was fitted on
  (<code>{{ atlas_id.encoder_built_with[:12] }}</code>){% endif %}. Coverage numbers are only
  comparable to numbers measured against the same three.</p>{% endif %}
  <p>Subject area and subregion names describe the reference text, not your
  records; the records quoted beside them are your own.</p>
  <p>{% if d.includes_evidence %}This file quotes your data. Re-run with
  <code>--no-evidence</code> before sharing it outside the dataset's trust boundary.
  {% else %}Record excerpts and source locations were omitted with <code>--no-evidence</code>.
  {% endif %}</p>
</footer>
</div>
"""



def _tokens_short(count: int | None) -> str:
    if not count:
        return "—"
    if count >= 1_000_000_000:
        return f"{count / 1e9:.1f}B"
    if count >= 1_000_000:
        return f"{count / 1e6:.1f}M"
    if count >= 1_000:
        return f"{count / 1e3:.0f}k"
    return f"{count:,}"


def _languages_shown(languages: list[tuple[str, float]]) -> list[tuple[str, float]]:
    """The language bars worth drawing: up to seven, and none under 0.1%.

    A corpus that is 98% one language still identifies sixty others from a
    handful of records each, and a bar for a share that rounds to nothing is a
    row the reader has to scroll past. The top three stay whatever their share
    so a small corpus does not lose its whole chart to the cut.
    """
    shown = [entry for entry in languages[:7] if entry[1] >= 0.001]
    return shown or languages[:3]


def _section_numbers(
    *,
    corpus: bool = False,
    problems: bool = False,
    budget: bool = False,
    atlas: bool = False,
    findings: bool = False,
    notes: bool = False,
    small_print: bool = False,
) -> dict[str, str]:
    """Number the sections that will actually render, in page order.

    The numbers used to be written into the markup, which was fine while every
    section always appeared. Most of them are conditional — a scan with no
    tokenizer prints no budget, and since the map moved to `dropoutt atlas` a
    scan report never has a section four — so a page could read 01, 02, 05, 06
    and leave the reader looking for the two that were never there.

    Both pages number from the same list. The scan report never has `findings`
    and the atlas page never has the other four; a section a page does not ask
    for gets an empty string and takes no number.
    """
    order = [
        ("corpus", corpus),
        ("problems", problems),
        ("budget", budget),
        ("atlas", atlas),
        ("findings", findings),
        ("notes", notes),
        ("small_print", small_print),
    ]
    numbers: dict[str, str] = {}
    n = 0
    for name, shown in order:
        if not shown:
            numbers[name] = ""
            continue
        n += 1
        numbers[name] = f"{n:02d}"
    return numbers


def render(
    result: ScanResult,
    fp: Fingerprint,
    budget: Any = None,
    *,
    include_evidence: bool = True,
    summary: ScanSummary | None = None,
) -> str:
    env = Environment(autoescape=True, undefined=StrictUndefined,
                      trim_blocks=True, lstrip_blocks=True)
    template = env.from_string(_TEMPLATE)
    s = summary or build(result, budget=budget, include_evidence=include_evidence)

    for problem in (*s.problems, *s.notes):
        for ev in problem.evidence:
            ev.excerpt = safe_snippet(ev.excerpt)
            if ev.partner_excerpt:
                ev.partner_excerpt = safe_snippet(ev.partner_excerpt)

    # Everything below is shared with the Markdown, JSON and terminal
    # renderings, and lives in `payload` so it cannot drift between them again.
    overlap = overlap_matrix(result)
    skipped = skipped_checks(result)
    off = (s.atlas.off_detail if s.atlas else {}) or {}
    off_examples = off_map_examples(result, s, include_evidence=include_evidence)
    has_tokenizer = result.ctx.tokenizer is not None

    root = result.ctx.root
    budget_table = budget_rows(budget)
    sec = _section_numbers(
        corpus=True, problems=True, budget=bool(budget_table),
        atlas=s.atlas is not None, notes=bool(s.notes), small_print=True,
    )
    return template.render(
        css=stylesheet(),
        logo=TEXT_LOGO_SVG,
        ratio=density_ratio,
        format_reach=format_reach,
        gradient=gradient(),
        grid_rows=GRID_ROWS,
        density_definition=DENSITY_DEFINITION,
        reach_definition=REACH_DEFINITION,
        imbalance_caption=IMBALANCE_CAPTION,
        sec=sec,
        atlas_no=sec["atlas"],
        atlas_title="Where your data sits",
        s=s,
        c=s.composition,
        problems=s.problems,
        notes=s.notes,
        root=root,
        root_short=root.rstrip("/").split("/")[-1] or root,
        tokens_short=_tokens_short(s.tokens),
        token_note=token_note(result, s),
        datasets=fp.datasets,
        languages_shown=_languages_shown(s.languages),
        overlap=overlap,
        budget=budget_table,
        budget_method=budget_method(budget, exact=has_tokenizer),
        budget_notes=list(getattr(budget, "notes", []) or []),
        has_tokenizer=has_tokenizer,
        skipped=skipped,
        degradations=result.ctx.degradations,
        provenance=sorted(fp.provenance.items()),
        fingerprint_id=fp.fingerprint_id,
        pipeline_version=fp.pipeline_version,
        # A coverage number means nothing without the coordinate system it was
        # measured in. The fingerprint has carried these since v1; the report a
        # person actually reads and forwards did not.
        atlas_id=atlas_identity(result),
        includes_evidence=include_evidence,
        shards=int(result.ctx.stats.get("shards", 1) or 1),
        off=off,
        off_by_dataset=sorted(
            ((k, v) for k, v in (off.get("by_dataset") or {}).items()),
            key=lambda kv: -kv[1]["rate"],
        )[:4],
        off_examples=off_examples,
    )


def render_atlas(
    result: ScanResult,
    *,
    include_evidence: bool = True,
    summary: ScanSummary | None = None,
) -> str:
    """The map as a self-contained page, with no scan report around it.

    Rendered in two passes: the shared section first, then the page it sits in.
    Jinja has no include without a loader, and giving this module one to fetch a
    string it already holds would be ceremony — the alternative, a second copy of
    the map's markup, is the thing this is written to avoid.
    """
    from .payload import build_atlas

    env = Environment(autoescape=True, undefined=StrictUndefined,
                      trim_blocks=True, lstrip_blocks=True)
    s = summary or build(result, include_evidence=include_evidence)
    data = build_atlas(result, include_evidence=include_evidence, summary=s)

    # Same rule as the scan report: a section that does not render does not
    # leave a hole behind it. Both are conditional — the map on a story existing,
    # the findings on either atlas check having fired.
    sec = _section_numbers(atlas=s.atlas is not None, findings=bool(data["findings"]))
    off = (s.atlas.off_detail if s.atlas else {}) or {}
    atlas_body = env.from_string(_ATLAS_SECTION).render(
        atlas_no="",
        atlas_title="Coverage",
        grid_rows=GRID_ROWS,
        s=s,
        ratio=density_ratio,
        format_reach=format_reach,
        gradient=gradient(),
        density_definition=DENSITY_DEFINITION,
        reach_definition=REACH_DEFINITION,
        imbalance_caption=IMBALANCE_CAPTION,
        off=off,
        off_by_dataset=sorted(
            ((k, v) for k, v in (off.get("by_dataset") or {}).items()),
            key=lambda kv: -kv[1]["rate"],
        )[:4],
        off_examples=off_map_examples(result, s, include_evidence=include_evidence),
    )

    root = result.ctx.root
    return env.from_string(_ATLAS_TEMPLATE).render(
        css=stylesheet(),
        logo=TEXT_LOGO_SVG,
        sec=sec,
        s=s,
        d=data,
        atlas_body=atlas_body,
        findings=data["findings"],
        atlas_id=atlas_identity(result),
        pipeline_version=PIPELINE_VERSION,
        root=root,
        root_short=root.rstrip("/").split("/")[-1] or root,
    )
