"""Configuration: inferred first, written to a versioned file, never asked for.

The chat template, special tokens and sequence length all come from the target
model's own config. The model card *is* the configuration, so ``--model`` is the
only thing the user has to supply, and even that is optional.

``dropoutt.toml`` is generated rather than authored, and lives in the repository
next to the data-preparation code so it is reviewed in pull requests and shared
across the team instead of living in one person's shell history.
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .chat_template import ChatTemplate
from .compat import HAVE_HF_HUB, HAVE_TOKENIZERS, json_loads
from .models import Profile, hash_many
from .registry_data import resolve_model_alias
from .tokenizer_panel import TokenizerHandle, load_tokenizer

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover
    tomllib = None

CONFIG_NAME = "dropoutt.toml"


def cache_dir() -> Path:
    """Where downloaded artifacts live.

    Honours ``DROPOUTT_CACHE`` then ``XDG_CACHE_HOME``, and falls back to a temp
    directory when the home directory is read-only, which is common on cluster
    compute nodes.
    """
    explicit = os.environ.get("DROPOUTT_CACHE")
    if explicit:
        return Path(explicit)
    base = os.environ.get("XDG_CACHE_HOME")
    candidate = Path(base) / "dropoutt" if base else Path.home() / ".cache" / "dropoutt"
    try:
        candidate.mkdir(parents=True, exist_ok=True)
        probe = candidate / ".writable"
        probe.touch()
        probe.unlink()
        return candidate
    except OSError:
        import tempfile  # noqa: PLC0415

        return Path(tempfile.gettempdir()) / "dropoutt-cache"


@dataclass
class Config:
    model: str | None = None
    profile: str = "auto"
    target: str | None = None
    seq_len: int | None = None
    tier: int = 1
    minhash_preset: str = "fineweb"
    mute: list[str] = field(default_factory=list)
    eval_sets: list[str] = field(default_factory=list)
    offline: bool = False

    def hash(self) -> str:
        return hash_many([
            str(self.model), self.profile, str(self.target), str(self.seq_len),
            str(self.tier), self.minhash_preset, ",".join(sorted(self.mute)),
        ])

    @classmethod
    def load(cls, root: Path) -> "Config":
        path = root / CONFIG_NAME if root.is_dir() else root.parent / CONFIG_NAME
        if not path.exists() or tomllib is None:
            return cls()
        try:
            data = tomllib.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return cls()
        scan = data.get("scan", {})
        return cls(
            model=scan.get("model"),
            profile=scan.get("profile", "auto"),
            target=scan.get("target"),
            seq_len=scan.get("seq_len"),
            tier=scan.get("tier", 1),
            minhash_preset=scan.get("minhash_preset", "fineweb"),
            mute=list(data.get("mute", {}).get("checks", [])),
            eval_sets=list(scan.get("eval_sets", [])),
            offline=scan.get("offline", False),
        )

    def to_toml(self, *, inferred_notes: dict[str, str] | None = None) -> str:
        notes = inferred_notes or {}

        def note(key: str) -> str:
            return f"  # {notes[key]}" if key in notes else ""

        lines = [
            "# dropoutt configuration.",
            "# Generated by `dropoutt init`. Edit rather than rewrite; the values below were",
            "# inferred from your data and from the target model's own config.",
            "",
            "[scan]",
            f'model = {self.model!r}{note("model")}' if self.model else "# model = \"Qwen/Qwen3-8B\"",
            f'profile = "{self.profile}"{note("profile")}',
        ]
        if self.target:
            lines.append(f'target = "{self.target}"  # declaring a target enables blocking')
        else:
            lines.append('# target = "sft"  # uncomment to let findings fail the run')
        if self.seq_len:
            lines.append(f'seq_len = {self.seq_len}{note("seq_len")}')
        lines += [
            f"tier = {self.tier}",
            f'minhash_preset = "{self.minhash_preset}"',
        ]
        if self.eval_sets:
            lines.append(f"eval_sets = {self.eval_sets!r}")
        lines += [
            "",
            "[mute]",
            "# Check ids to silence, with a reason. Muting is a decision worth reviewing.",
            f"checks = {self.mute!r}",
            "",
        ]
        return "\n".join(lines)


@dataclass
class ResolvedModel:
    model_id: str
    tokenizer: TokenizerHandle | None
    chat_template: ChatTemplate | None
    seq_len: int | None
    notes: list[str] = field(default_factory=list)


def resolve_model(model: str, *, offline: bool = False) -> ResolvedModel:
    """Load everything the model card can tell us."""
    model_id = resolve_model_alias(model)
    notes: list[str] = []

    tok = load_tokenizer(model_id, offline=offline)
    if tok is None:
        if not HAVE_TOKENIZERS:
            notes.append("tokenizers not installed; install 'dropoutt[tokenizer]'")
        else:
            notes.append(f"could not load a tokenizer for {model_id}")
        return ResolvedModel(model_id, None, None, None, notes)

    cfg = _load_tokenizer_config(model_id, offline=offline)
    template_src = cfg.get("chat_template")
    chat_template = None
    if isinstance(template_src, str) and template_src.strip():
        try:
            chat_template = ChatTemplate(
                source=template_src,
                bos_token=_token_str(cfg.get("bos_token")),
                eos_token=_token_str(cfg.get("eos_token")),
                pad_token=_token_str(cfg.get("pad_token")),
                unk_token=_token_str(cfg.get("unk_token")),
                additional_special_tokens=[
                    t for t in (cfg.get("additional_special_tokens") or [])
                    if isinstance(t, str)
                ],
                model_id=model_id,
                template_hash=hash_many([template_src]),
            )
        except Exception as exc:  # noqa: BLE001
            notes.append(f"chat template failed to compile: {type(exc).__name__}: {exc}")
    elif cfg:
        notes.append(f"{model_id} declares no chat_template")

    seq_len = cfg.get("model_max_length")
    if isinstance(seq_len, int) and seq_len > 1_000_000:
        seq_len = None  # sentinel value some configs use for "unbounded"

    return ResolvedModel(model_id, tok, chat_template, seq_len, notes)


def _token_str(value: Any) -> str | None:
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        content = value.get("content")
        return content if isinstance(content, str) else None
    return None


def _load_tokenizer_config(model_id: str, *, offline: bool = False) -> dict[str, Any]:
    local = Path(model_id) / "tokenizer_config.json"
    if local.exists():
        try:
            return json_loads(local.read_text(encoding="utf-8"))
        except Exception:
            return {}
    if offline or not HAVE_HF_HUB:
        return {}
    try:
        from huggingface_hub import hf_hub_download  # noqa: PLC0415

        path = hf_hub_download(model_id, "tokenizer_config.json",
                               cache_dir=str(cache_dir() / "hub"))
        return json_loads(Path(path).read_text(encoding="utf-8"))
    except Exception:
        return {}


def parse_profile(value: str) -> Profile:
    try:
        return Profile(value)
    except ValueError:
        return Profile.UNKNOWN
